# Permalinks
#
permalink:           /:categories/:year/:month/:day/:title/

# Setup
title:               Jason's Lanyon Test
tagline:             Why Shouldn't My Site Look Nice?
description:         Some Amazing Description
url:                 http://yoururl.com
baseurl:             https://scribal-io.github.io/lanyon/
paginate:            5

# Plugins, Tags, Categories and Analytics  
plugins:          [jekyll-paginate]

# About/contact
author:
  name:              Jason Horowitz
  url:               https://yoururl.com
  email:             you@gmail.com
  
# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
